#include "dump.hpp"
#include "mediatypes.hpp"

#include <QMetaProperty>

namespace debug
{

void
dump_list_model (
    const QLoggingCategory &cat,
    const QAbstractListModel &list,
    const QString &display_list_name,
    bool dump_nested_lists
)
{
    qCDebug (cat) << "--- Dumping " << display_list_name << "via QAbstractItemModel interface ---";

    // Get the role map (exactly what QML does while booting)
    const QHash<int, QByteArray> roles = list.roleNames();
    const int rowCount = list.rowCount();

    qCDebug (cat) << "Detected rows:" << rowCount;

    // Iterate over every row using model indices
    for (int row = 0; row < rowCount; ++row) {
        QModelIndex idx = list.index(row, 0);
        qCDebug (cat).nospace() << "\n[Row " << row << "]";

        // Iterate over every role available for this row
        for (auto it = roles.cbegin(); it != roles.cend(); ++it) {
            const int roleId = it.key();
            const QByteArray &roleName = it.value();
            
            // Extract the data using the std::visit evaluator
            QVariant roleData = list.data(idx, roleId);

            // Make it readable on console
            if (roleName != "songs") {
                qCDebug (cat).nospace() << "  -> " << roleName << " : " << roleData;
                continue;
            }

            if (!roleData.canConvert<QList<Types::Song>>()) {
                qCDebug (cat).nospace() 
                    << "  -> " << roleName
                    << " : [Error: this QVariant cannot convert to QList<Types::Song>]";
                continue;

            } 

            auto songList = roleData.value<QList<Types::Song>>();
            qCDebug (cat).nospace() << "  -> " << roleName << " : [List of " << songList.size() << " songs]";

            // Unwrap the nested list iterating over Q_GADGET properties
            if (!dump_nested_lists || songList.isEmpty()) {
                continue;
            } 
            
            // Extract the info generated by MOC for Types::Song
            const QMetaObject &meta = Types::Song::staticMetaObject;
            int propCount = meta.propertyCount();

            for (int i = 0; i < songList.size(); ++i) {
                qCDebug(cat).nospace() << "      [" << i << "] Types::Song {";
                
                // Need a constant pointer to the current gadget to read it
                const Types::Song *songPtr = &songList.at(i);
                
                // Iterate over the exposed properties
                for (int p = 0; p < propCount; ++p) {
                    QMetaProperty prop = meta.property(p);
                    QVariant propValue = prop.readOnGadget(songPtr);
                    
                    qCDebug(cat).nospace() << "        ." << prop.name() << " : " << propValue;
                }
                qCDebug(cat).nospace() << "      }";
            }
        }
    }

    qCDebug (cat) << "-------------------------------------------------------------";
}

}