#pragma once

#include <QAbstractListModel>
#include <QtQmlIntegration/qqmlintegration.h>
#include <QUrl>
#include <QString>
#include <QList>
#include <qlist.h>
#include <variant>
#include <vector>

#include <functional>

/// All the forms of identifiable structures of audio that this player supports.
namespace Types {

    struct Song {
        QString title;
        QString artist;
        QString album;
        quint64 duration; // ms
        QUrl    source; // to the audio path
        QUrl    cover;
    };

    struct Album {
        QString      title;
        QString      artist;
        QList<Song>  songs;
        QUrl         cover;

        // sum of all the children
        quint64 duration() const {
            quint64 total = 0;
            for (const Song &s : songs)
                total += s.duration;
            return total;
        }
    };

    using Playlist = Album;

    using Any = std::variant<Song, Album>;
}

/// Role definition. Enables automatic QML role generation.
struct CompiledRole {
    int number;
    QByteArray name;
    std::function<QVariant(const Types::Any &)> extractor;
};

/**
    @brief Unidirectional, read-only callback that extracts a specific property from a media metadata container.
    
    @details This functional wrapper processes a read-only reference to a dynamic item (`const Types::Any&`),
    which can hold distinct underlying data types like Types::Song, Types::Album, or Types::Playlist.
    It inspects the variant's active type at runtime—typically using std::visit—and projects the requested 
    field into a QVariant returned by value.

    @note This extractor is strictly read-only. It provides a copy of the data, meaning it does not support 
    writing back to the source or bidirectional QML assignments through itself.
*/
using RoleExtractor = std::function<QVariant(const Types::Any &)>;
using RoleExtractor   = std::function<QVariant(const Types::Any &)>; 

/**
    @brief Gives the developer simplified controls to define roles.
    A good example on how to do it is defaultroles.hpp.
*/
using RoleDefinition  = std::pair<QByteArray, RoleExtractor>;
using RoleDefinitions = std::vector<RoleDefinition>;


/**
    @brief List of any form of playable media, enumerated in the Types:: namespace. 
    This is not intended to be instantiated directly but rather to use one of the inherited classes.

    Inherited classes can restrict themselves to only hold 1 or more specified types and update
    their add(T) and remove(T) functions accordingly.
*/
class AbstractMediaSequence : public QAbstractListModel {
    Q_OBJECT
    QML_ANONYMOUS

private:
    const RoleDefinitions     m_roledefs;          // actual role definitions
    std::vector<CompiledRole> m_compiledroles;     // roles held, autogenerated by code (needs to be made const-after-construction again)
    QList<Types::Any>         m_items;

public:
    explicit AbstractMediaSequence(QObject *parent, std::vector<std::pair<QByteArray, RoleExtractor>> role_defs);

    int                    rowCount(const QModelIndex &parent = QModelIndex())        const override;
    QVariant               data(const QModelIndex &index, int role = Qt::DisplayRole) const override;
    QHash<int, QByteArray> roleNames()                                                const override;

    QList<Types::Any> items() const;

    // items that can be converted to certain type
    template <typename media_type>
    QList<media_type> items() const 
    {
        QList<media_type> filtered_list;
        
        filtered_list.reserve(m_items.size());

        for (const Types::Any &item : m_items) {
            // verify if the variant holds the type
            if (std::holds_alternative<media_type>(item)) {
                filtered_list.append(std::get<media_type>(item));
            }
        }

        return filtered_list;
    }

protected:
    // Inherited models call these to manipulate the container
    void append(const Types::Any &item);

    template <typename Container>
    requires
        std::ranges::forward_range<Container> // Any type of list
    &&  std::convertible_to<typename Container::value_type, typename decltype(m_items)::value_type> // that can be contained by m_items
    void
    batch_append(const Container &items)
    {
        if (items.empty()) return;

        // Notify to QML views the entire block insertion at once
        int first_row = rowCount();
        int last_row = first_row + static_cast<int>(items.size()) - 1;

        beginInsertRows({}, first_row, last_row);
        
        // Perform the insertion
        for (const Types::Any &item : items) {
            m_items.push_back(item);
        }

        endInsertRows();
    }
    
    void remove(int index);
    void clear();

    // Access to the raw item for inherited classes that need extra roles
    const Types::Any &itemAt(int index) const;
    int itemCount() const;
};