#pragma once

#include <QAbstractListModel>
#include <QtQmlIntegration/qqmlintegration.h>
#include <QUrl>
#include <QString>
#include <QList>
#include <variant>
#include <vector>

#include <functional>

/**
    @brief All the forms of identifiable structures of audio that this player supports.
*/
namespace Types {

    struct Song {
        QString title;
        QString artist;
        QString album;
        qint64  duration; // ms
        QUrl    source; // to the audio path
        QUrl    cover;
    };

    struct Album {
        QString      title;
        QString      artist;
        QList<Song>  songs;
        QUrl         cover;

        // sum of all the children
        qint64 duration() const {
            qint64 total = 0;
            for (const Song &s : songs)
                total += s.duration;
            return total;
        }
    };

    using Playlist = Album;

    // abstract identifier - can mix all types by default
    using Any      = std::variant<Song, Album>;
}

// Role definition. Enables automatic QML role generation.
struct CompiledRole {
    int number;
    QByteArray name;
    std::function<QVariant(const Types::Any &)> extractor;
};

// Returns the value for given role
using RoleExtractor   = std::function<QVariant(const Types::Any &)>;
using RoleDefinition  = std::pair<QByteArray, RoleExtractor>;
using RoleDefinitions = std::vector<RoleDefinition>;


/**
    @brief List model that can contain any type of identifiable audio metadata organization forms, referred as "AudioFormTypes" at the beginning of this file.
    This is not intended to be instantiated directly but rather to use one of the inherited classes.

    The intention is that inherited classes will restrict themselves to only hold 1 or more specified types and update their add(T) and remove(T) functions accordingly.
*/
class AbstractModel : public QAbstractListModel {
    Q_OBJECT
    QML_ANONYMOUS

public:
    explicit AbstractModel(QObject *parent, std::vector<std::pair<QByteArray, RoleExtractor>> role_defs);

    int      rowCount(const QModelIndex &parent = QModelIndex()) const override;
    QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const override;
    QHash<int, QByteArray> roleNames() const override;

protected:
    // Inherited models call these to manipulate the container
    void append(const Types::Any &item);
    void remove(int index);
    void clear();

    // Access to the raw item for inherited classes that need extra roles
    const Types::Any &itemAt(int index) const;
    int itemCount() const;

private:
    const RoleDefinitions m_roledefs; // actual role definitions
    std::vector<CompiledRole> m_compiledroles;      // roles held, autogenerated by code (needs to be made const-after-construction again)
    std::vector<Types::Any> m_items;
};