#pragma once

#include "coverprovider.hpp"
#include "defaultroles.hpp"
#include "mediatypes.hpp"

#include <QAbstractItemModel>
#include <QFuture>
#include <QLoggingCategory>
#include <QReadWriteLock>

#include <QtQmlIntegration/qqmlintegration.h>


Q_DECLARE_LOGGING_CATEGORY(l_mediasequences)


/**
    @brief List of any form of playable media, enumerated in the Types:: namespace. 
    This is not intended to be instantiated directly but rather to use one of the inherited classes.

    Inherited classes can restrict themselves to only hold 1 or more specified types and update
    their add(T) and remove(T) functions accordingly.
*/
class AbstractMediaSequence : public QAbstractListModel {
    Q_OBJECT
    QML_ANONYMOUS

    Q_PROPERTY (qsizetype count READ rowCount NOTIFY countChanged)

private:
    const RoleDefinitions     m_roledefs;          // actual role definitions
    std::vector<CompiledRole> m_compiledroles;     // roles held, autogenerated by code (needs to be made const-after-construction again)
    QList<Types::Any>         m_items;

public:
    explicit AbstractMediaSequence(QObject *parent, std::vector<std::pair<QByteArray, RoleExtractor>> role_defs);

    int                    rowCount(const QModelIndex &parent = QModelIndex())        const override;
    QVariant               data(const QModelIndex &index, int role = Qt::DisplayRole) const override;
    QHash<int, QByteArray> roleNames()                                                const override;

    std::optional<int>     roleNumber(const QByteArray &role) const;

    const decltype(m_items) & items() const;

    // proxy for both sources
    static QStringList sources (const QList<Types::Any> &items);
    std::optional<std::reference_wrapper<Types::Any>> pointed_to(const QPersistentModelIndex &idx);
    std::optional<size_t> row_pointed_to(const QPersistentModelIndex &idx) const;

    QStringList sources () const; // return the source or path component of all items

    // Access to the raw item for inherited classes that need extra roles
    std::optional<std::reference_wrapper<Types::Any>> item_at(size_t index);
    int itemCount() const;

    // read a role directly
    Q_INVOKABLE QVariant readRole(qsizetype row, const QByteArray &role) const;

    // items that can be converted to certain type
    template <typename media_type>
    QList<media_type> items() const 
    {
        QList<media_type> filtered_list;

        QReadLocker locker (&m_lock);
        
        filtered_list.reserve(m_items.size());

        for (const Types::Any &item : m_items) {
            // verify if the variant holds the type
            if (std::holds_alternative<media_type>(item)) {
                filtered_list.append(std::get<media_type>(item));
            }
        }

        return filtered_list;
    }

    // sources of convertibles to this type
    template <typename media_type>
    QStringList sources() const
    {
        QReadLocker locker(&m_lock);
        QStringList uri_sources;

        for (const Types::Any &item : m_items) {
            // Check if the variant holds the requested type
            if (const auto *resolved = std::get_if<media_type>(&item)) {
                
                // Extract the field depending on what type was requested
                if constexpr (std::is_same_v<media_type, Types::Song>) {
                    uri_sources.append(resolved->source.toLocalFile());
                }
            }
        }

        return uri_sources;
    }

    // Find an item whose pointed member matches the needle, returns invalid if not found
    template <typename MediaType, typename FieldType>
    QPersistentModelIndex find(FieldType MediaType::* member, const FieldType &needle) const
    {
        QReadLocker locker (&m_lock);

        for (size_t i = 0; i < m_items.size(); ++i) {
            
            // Pass the address of the variant to std::get_if to safely check its active type
            if (const MediaType *actual_media = std::get_if<MediaType>(&m_items.at(i))) {
                
                // Apply the pointer-to-member operator (->*) to evaluate the target field
                if (actual_media->*member == needle) {
                    return index(static_cast<int>(i));
                }
            }
        }

        // invalid if not found
        return QPersistentModelIndex();
    }

signals:
    void countChanged();

protected:
    // Inherited models call these to manipulate the container
    QPersistentModelIndex append(const Types::Any &item);

    template <typename Container>
    requires
        std::ranges::forward_range<Container> // Any type of list
    &&  std::convertible_to<typename Container::value_type, typename decltype(m_items)::value_type> // that can be contained by m_items
    QList<QPersistentModelIndex>
    batch_append(const Container &items)
    {
        // ready to use indices for right after manipulation
        QList<QPersistentModelIndex> indices; 
        
        if (items.empty()) return indices;

        // Filter only valid items before appending
        std::vector<Types::Any> valid_items;
        valid_items.reserve(items.size());

        for (const Types::Any &item : items) {

            // if such item is actually a Types::Song and its source is empty, continue;
            if (
                std::holds_alternative<Types::Song>(item)
            &&  std::get<Types::Song>(item).source.isEmpty())
            {
                continue;
            }

            valid_items.push_back(item);
        }

        if (valid_items.empty()) return indices;

        // Notify to QML views the entire block insertion at once
        int first_row = rowCount();
        int last_row = first_row + static_cast<int>(valid_items.size()) - 1;

        beginInsertRows({}, first_row, last_row);

        {
            QWriteLocker locker (&m_lock);

            // prepare the QList for the append
            m_items.reserve(m_items.size() + valid_items.size());
        
            // count how many rows we've appended
            size_t current_row = first_row;

            for (Types::Any &valid_item : valid_items) {
                // how do I know the index the push_back ended up on?
                m_items.push_back(std::move(valid_item));

                // generate the persistent model index for the row we just filled 
                indices.append(index(current_row));

                current_row++;
            }
        }   

        endInsertRows();

        emit countChanged();

        return indices;
    }

    // only extract songs metadata
    QFuture<void> batch_append (const QList<QUrl> &sources, std::shared_ptr<cover_provider> provider);

    // remove items in batch using their persistent indices
    void batch_remove (const QList<QPersistentModelIndex> &items);

    std::optional<size_t> __row_pointed_to_unlocked (const QPersistentModelIndex &idx) const;

    mutable QReadWriteLock m_lock;
    
    void remove(size_t index);
    void clear();
};