#pragma once

#include <QAbstractListModel>
#include <QtQmlIntegration/qqmlintegration.h>
#include <QList>
#include <QAbstractItemModel>
#include <QList>
#include <QFuture>
#include <variant>
#include <vector>

#include "coverprovider.hpp"
#include "defaultroles.hpp"
#include "mediatypes.hpp"

/**
    @brief List of any form of playable media, enumerated in the Types:: namespace. 
    This is not intended to be instantiated directly but rather to use one of the inherited classes.

    Inherited classes can restrict themselves to only hold 1 or more specified types and update
    their add(T) and remove(T) functions accordingly.
*/
class AbstractMediaSequence : public QAbstractListModel {
    Q_OBJECT
    QML_ANONYMOUS

private:
    const RoleDefinitions     m_roledefs;          // actual role definitions
    std::vector<CompiledRole> m_compiledroles;     // roles held, autogenerated by code (needs to be made const-after-construction again)
    QList<Types::Any>         m_items;

public:
    explicit AbstractMediaSequence(QObject *parent, std::vector<std::pair<QByteArray, RoleExtractor>> role_defs);

    int                    rowCount(const QModelIndex &parent = QModelIndex())        const override;
    QVariant               data(const QModelIndex &index, int role = Qt::DisplayRole) const override;
    QHash<int, QByteArray> roleNames()                                                const override;

    QList<Types::Any> items() const;

    // Access to the raw item for inherited classes that need extra roles
    const Types::Any &itemAt(int index) const;
    int itemCount() const;

    // items that can be converted to certain type
    template <typename media_type>
    QList<media_type> items() const 
    {
        QList<media_type> filtered_list;
        
        filtered_list.reserve(m_items.size());

        for (const Types::Any &item : m_items) {
            // verify if the variant holds the type
            if (std::holds_alternative<media_type>(item)) {
                filtered_list.append(std::get<media_type>(item));
            }
        }

        return filtered_list;
    }

    QPersistentModelIndex find (const Types::Any &needle) const;

protected:
    // Inherited models call these to manipulate the container
    void append(const Types::Any &item);

    template <typename Container>
    requires
        std::ranges::forward_range<Container> // Any type of list
    &&  std::convertible_to<typename Container::value_type, typename decltype(m_items)::value_type> // that can be contained by m_items
    void
    batch_append(const Container &items)
    {
        if (items.empty()) return;

        // Filter only valid items before appending
        std::vector<Types::Any> valid_items;
        valid_items.reserve(items.size());

        for (const Types::Any &item : items) {

            // if such item is actually a Types::Song and its source is empty, continue;
            if (
                std::holds_alternative<Types::Song>(item)
            &&  std::get<Types::Song>(item).source.isEmpty())
            {
                continue;
            }

            valid_items.push_back(item);
        }

        if (valid_items.empty()) return;

        // Notify to QML views the entire block insertion at once
        int first_row = rowCount();
        int last_row = first_row + static_cast<int>(valid_items.size()) - 1;

        beginInsertRows({}, first_row, last_row);

        // prepare the QList for the append
        m_items.reserve(m_items.size() + valid_items.size());
    
        for (Types::Any &valid_item : valid_items) {
            m_items.push_back(std::move(valid_item));
        }

        endInsertRows();
    }

    // only extract songs metadata
    QFuture<void> batch_append (const QList<QUrl> &sources, std::shared_ptr<cover_provider> provider);
    
    void remove(int index);
    void clear();
};